trained_model: 'weights/craft_mlt_25k.pth'          # pretrained model
text_threshold: 0.7                                 # text confidence threshold
low_text: 0.4                                       # text low-bound score
link_threshold: 0.4                                 # link confidence threshold
cuda: True                                          # Use cuda for inference
canvas_size: 1280                                   # image size for inference
mag_ratio: 1.5                                      # image magnification ratio
poly: False                                         # enable polygon type
show_time: False                                    # show processing time
test_folder: 'data'                                 # folder path to input images
refine: False                                       # enable link refiner
refiner_model: 'weights/craft_refiner_CTW1500.pth'  # pretrained refiner model
